import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans, Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sileo";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/components/custom/common/navbar";
const notoSansHeading = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Footer from "@/components/custom/common/footer";
import QueryClint from "@/lib/QueryClint";

const publicSans = Public_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        publicSans.variable,
        notoSansHeading.variable,
      )}
    >
      <TooltipProvider>
        <QueryClint>
          <NuqsAdapter>
            <body className="min-h-full flex flex-col">
              <Navbar />
              {children}
              <Footer />
              <Toaster position="top-center" />
            </body>
          </NuqsAdapter>
        </QueryClint>
      </TooltipProvider>
    </html>
  );
}
